#!/usr/bin/env python3
"""Bound the audio_interact volume so a full disk stops taking the hub down.

This exists because the disk filling is not a one-off. It has now been cleared
by hand twice, and each time the visible symptom was somewhere else entirely:

    OSError: [Errno 28] No space left on device: '/app/data/devices.json.tmp'
    POST /api/heartbeat  500

device_hub writes its state file on every heartbeat, so when the disk fills the
hub stops acknowledging anything and commands appear not to reach the device.
Two separate debugging sessions went looking at MQTT and at delivery latency
before anyone ran df. A volume that grows without bound is not an audio problem,
it is an availability problem for everything sharing the filesystem.

Inflow is roughly 3.6 GB/day right now, much of it generated by AEC test runs:
every cloud ASR call lands a session recording here. On a 40 GB disk that is
about eleven days from empty to full, so age alone cannot bound it -- a 14-day
policy still overflows. Hence two rules:

  1. age    -- drop date directories older than --keep-days. Cheap and obvious.
  2. water  -- if free space is below --min-free-gb, keep dropping the OLDEST
               remaining date directory until free space reaches --target-free-gb.

Rule 2 is what actually bounds the disk, because it responds to the thing that
matters (free bytes) rather than to a guess about inflow rate. Rule 1 just keeps
the normal case tidy so rule 2 rarely has to act.

Deletion is always oldest-first and always whole date directories. It never
looks inside a day, never deletes today, and never deletes the newest
--floor-days worth no matter how tight the disk gets -- if the disk is so full
that the floor is in the way, that is a capacity problem a cleanup script must
not paper over, and it says so and exits non-zero.

Dry run by default. Pass --apply to actually delete.

    python3 prune_audio_interact.py                 # show what it would do
    sudo python3 prune_audio_interact.py --apply    # do it
"""
import argparse
import datetime as dt
import os
import re
import shutil
import sys
from pathlib import Path

DEFAULT_ROOT = Path("/var/lib/docker/volumes/"
                    "wangyutang_platform_audio_interact_data/_data")
# Only these are date-partitioned and safe to prune wholesale. settings.json and
# anything unrecognised is left strictly alone.
PRUNABLE = ("sessions", "recordings", "segments")
DATE_DIR = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def free_gb(path: Path) -> float:
    st = os.statvfs(path)
    return st.f_bavail * st.f_frsize / 1024**3


def dir_bytes(path: Path) -> int:
    total = 0
    for dirpath, _, names in os.walk(path):
        for n in names:
            try:
                total += os.lstat(os.path.join(dirpath, n)).st_size
            except OSError:
                pass
    return total


def collect(root: Path):
    """Every date directory under the prunable subtrees, newest last."""
    found = []
    for sub in PRUNABLE:
        base = root / sub
        if not base.is_dir():
            continue
        for child in base.iterdir():
            if child.is_dir() and DATE_DIR.match(child.name):
                try:
                    day = dt.date.fromisoformat(child.name)
                except ValueError:
                    continue
                found.append((day, child))
    found.sort(key=lambda p: p[0])
    return found


def human(n: int) -> str:
    return f"{n / 1024**3:.2f}G" if n >= 1024**3 else f"{n / 1024**2:.0f}M"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    ap.add_argument("--keep-days", type=int, default=7)
    ap.add_argument("--min-free-gb", type=float, default=6.0)
    ap.add_argument("--target-free-gb", type=float, default=10.0)
    # Never delete the newest N days, whatever the disk looks like. Recent
    # sessions are the ones someone might still want to listen to, and a script
    # that deletes today's data to buy an hour of headroom has made the problem
    # invisible rather than smaller.
    ap.add_argument("--floor-days", type=int, default=2)
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    if not args.root.is_dir():
        sys.exit(f"no such volume root: {args.root}")

    today = dt.date.today()
    entries = collect(args.root)
    if not entries:
        print(f"{args.root}: 没有可清理的日期目录")
        return 0

    floor = today - dt.timedelta(days=args.floor_days)
    cutoff = today - dt.timedelta(days=args.keep_days)
    print(f"root      {args.root}")
    print(f"free      {free_gb(args.root):.1f}G  (低于 {args.min_free_gb}G 才启动水位清理)")
    print(f"日期目录  {len(entries)} 个，{entries[0][0]} .. {entries[-1][0]}")
    print(f"保留      {args.keep_days} 天以内；{floor} 及之后的绝不删")
    print()

    doomed = []

    # Rule 1: age.
    for day, path in entries:
        if day < cutoff and day < floor:
            doomed.append((day, path, "过期"))

    # Rule 2: watermark. Simulate the age deletions first so the two rules do
    # not both claim credit for the same freed bytes.
    if free_gb(args.root) < args.min_free_gb:
        projected = free_gb(args.root) + sum(
            dir_bytes(p) for _, p, _ in doomed) / 1024**3
        claimed = {p for _, p, _ in doomed}
        for day, path in entries:
            if projected >= args.target_free_gb:
                break
            if path in claimed or day >= floor:
                continue
            projected += dir_bytes(path) / 1024**3
            doomed.append((day, path, "水位"))
        if projected < args.target_free_gb:
            print(f"!! 即使删光 {floor} 之前的全部数据，也只能到 "
                  f"{projected:.1f}G，达不到目标 {args.target_free_gb}G。")
            print("!! 这是容量不足，不是清理不够。不要靠放宽 --floor-days 掩盖。")
            return 1

    if not doomed:
        print("无需清理。")
        return 0

    doomed.sort(key=lambda d: d[0])
    total = 0
    for day, path, why in doomed:
        size = dir_bytes(path)
        total += size
        rel = path.relative_to(args.root)
        print(f"  {'删除' if args.apply else '将删'}  {rel}  {human(size)}  ({why})")
        if args.apply:
            shutil.rmtree(path)

    print()
    print(f"{'已释放' if args.apply else '可释放'} {human(total)}"
          f"（{len(doomed)} 个目录）")
    if args.apply:
        print(f"free 现在 {free_gb(args.root):.1f}G")
    else:
        print("这是演练。加 --apply 才会真的删除。")
    return 0


if __name__ == "__main__":
    sys.exit(main())
